//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: mongorpc.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf

/// Usage: instantiate `Mongorpc_MongoRPCClient`, then call methods of this protocol to make API calls.
internal protocol Mongorpc_MongoRPCClientProtocol: GRPCClient {
    var serviceName: String { get }
    var interceptors: Mongorpc_MongoRPCClientInterceptorFactoryProtocol? { get }

    func listCollections(
        _ request: Mongorpc_ListCollectionsRequest,
        callOptions: CallOptions?
    ) -> UnaryCall<Mongorpc_ListCollectionsRequest, Mongorpc_ListCollectionsResponse>
}

extension Mongorpc_MongoRPCClientProtocol {
    var serviceName: String {
        return "mongorpc.MongoRPC"
    }

    /// Unary call to ListCollections
    ///
    /// - Parameters:
    ///   - request: Request to send to ListCollections.
    ///   - callOptions: Call options.
    /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
    func listCollections(
        _ request: Mongorpc_ListCollectionsRequest,
        callOptions: CallOptions? = nil
    ) -> UnaryCall<Mongorpc_ListCollectionsRequest, Mongorpc_ListCollectionsResponse> {
        return makeUnaryCall(
            path: "/mongorpc.MongoRPC/ListCollections",
            request: request,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeListCollectionsInterceptors() ?? []
        )
    }
}

internal protocol Mongorpc_MongoRPCClientInterceptorFactoryProtocol {
    /// - Returns: Interceptors to use when invoking 'listCollections'.
    func makeListCollectionsInterceptors() -> [ClientInterceptor<Mongorpc_ListCollectionsRequest, Mongorpc_ListCollectionsResponse>]
}

internal final class Mongorpc_MongoRPCClient: Mongorpc_MongoRPCClientProtocol {
    internal let channel: GRPCChannel
    internal var defaultCallOptions: CallOptions
    internal var interceptors: Mongorpc_MongoRPCClientInterceptorFactoryProtocol?

    /// Creates a client for the mongorpc.MongoRPC service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    internal init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Mongorpc_MongoRPCClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}
