// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mongorpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// `NullValue` is a singleton enumeration to represent the null value for the
/// `Value` type union.
///
///  The JSON representation for `NullValue` is JSON `null`.
enum Mongorpc_NullValue: SwiftProtobuf.Enum {
    typealias RawValue = Int

    /// Null value.
    case nullValue // = 0
    case UNRECOGNIZED(Int)

    init() {
        self = .nullValue
    }

    init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .nullValue
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
        case .nullValue: return 0
        case let .UNRECOGNIZED(i): return i
        }
    }
}

#if swift(>=4.2)

    extension Mongorpc_NullValue: CaseIterable {
        // The compiler won't synthesize support with the UNRECOGNIZED case.
        static var allCases: [Mongorpc_NullValue] = [
            .nullValue,
        ]
    }

#endif // swift(>=4.2)

struct Mongorpc_LatLng {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The latitude in degrees. It must be in the range [-90.0, +90.0].
    var latitude: Double = 0

    /// The longitude in degrees. It must be in the range [-180.0, +180.0].
    var longitude: Double = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

struct Mongorpc_Timestamp {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Represents seconds of UTC time since Unix epoch
    /// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
    /// 9999-12-31T23:59:59Z inclusive.
    var seconds: Int64 = 0

    /// Non-negative fractions of a second at nanosecond resolution. Negative
    /// second values with fractions must still have non-negative nanos values
    /// that count forward in time. Must be from 0 to 999,999,999
    /// inclusive.
    var nanos: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

/// An array value.
struct Mongorpc_ArrayValue {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Values in the array.
    var values: [Mongorpc_Value] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

/// A map value.
struct Mongorpc_MapValue {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The map's fields.
    ///
    /// The map keys represent field names. Field names matching the regular
    /// expression `__.*__` are reserved. Reserved field names are forbidden except
    /// in certain documented contexts. The map keys, represented as UTF-8, must
    /// not exceed 1,500 bytes and cannot be empty.
    var fields: [String: Mongorpc_Value] = [:]

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

/// A message that can hold any of the supported value types.
struct Mongorpc_Value {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Must have a value set.
    var valueType: Mongorpc_Value.OneOf_ValueType?

    /// A null value.
    var nullValue: Mongorpc_NullValue {
        get {
            if case let .nullValue(v)? = valueType { return v }
            return .nullValue
        }
        set { valueType = .nullValue(newValue) }
    }

    /// A boolean value.
    var booleanValue: Bool {
        get {
            if case let .booleanValue(v)? = valueType { return v }
            return false
        }
        set { valueType = .booleanValue(newValue) }
    }

    /// An integer value.
    var integerValue: Int64 {
        get {
            if case let .integerValue(v)? = valueType { return v }
            return 0
        }
        set { valueType = .integerValue(newValue) }
    }

    /// A double value.
    var doubleValue: Double {
        get {
            if case let .doubleValue(v)? = valueType { return v }
            return 0
        }
        set { valueType = .doubleValue(newValue) }
    }

    /// A timestamp value.
    ///
    /// Precise only to microseconds. When stored, any additional precision is
    /// rounded down.
    var timestampValue: Mongorpc_Timestamp {
        get {
            if case let .timestampValue(v)? = valueType { return v }
            return Mongorpc_Timestamp()
        }
        set { valueType = .timestampValue(newValue) }
    }

    /// A string value.
    ///
    /// The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
    /// Only the first 1,500 bytes of the UTF-8 representation are considered by
    /// queries.
    var stringValue: String {
        get {
            if case let .stringValue(v)? = valueType { return v }
            return String()
        }
        set { valueType = .stringValue(newValue) }
    }

    /// A bytes value.
    ///
    /// Must not exceed 1 MiB - 89 bytes.
    /// Only the first 1,500 bytes are considered by queries.
    var bytesValue: Data {
        get {
            if case let .bytesValue(v)? = valueType { return v }
            return Data()
        }
        set { valueType = .bytesValue(newValue) }
    }

    /// A geo point value representing a point on the surface of Earth.
    var geoPointValue: Mongorpc_LatLng {
        get {
            if case let .geoPointValue(v)? = valueType { return v }
            return Mongorpc_LatLng()
        }
        set { valueType = .geoPointValue(newValue) }
    }

    /// An array value.
    ///
    /// Cannot directly contain another array value, though can contain an
    /// map which contains another array.
    var arrayValue: Mongorpc_ArrayValue {
        get {
            if case let .arrayValue(v)? = valueType { return v }
            return Mongorpc_ArrayValue()
        }
        set { valueType = .arrayValue(newValue) }
    }

    /// A map value.
    var mapValue: Mongorpc_MapValue {
        get {
            if case let .mapValue(v)? = valueType { return v }
            return Mongorpc_MapValue()
        }
        set { valueType = .mapValue(newValue) }
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    /// Must have a value set.
    enum OneOf_ValueType: Equatable {
        /// A null value.
        case nullValue(Mongorpc_NullValue)
        /// A boolean value.
        case booleanValue(Bool)
        /// An integer value.
        case integerValue(Int64)
        /// A double value.
        case doubleValue(Double)
        /// A timestamp value.
        ///
        /// Precise only to microseconds. When stored, any additional precision is
        /// rounded down.
        case timestampValue(Mongorpc_Timestamp)
        /// A string value.
        ///
        /// The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
        /// Only the first 1,500 bytes of the UTF-8 representation are considered by
        /// queries.
        case stringValue(String)
        /// A bytes value.
        ///
        /// Must not exceed 1 MiB - 89 bytes.
        /// Only the first 1,500 bytes are considered by queries.
        case bytesValue(Data)
        /// A geo point value representing a point on the surface of Earth.
        case geoPointValue(Mongorpc_LatLng)
        /// An array value.
        ///
        /// Cannot directly contain another array value, though can contain an
        /// map which contains another array.
        case arrayValue(Mongorpc_ArrayValue)
        /// A map value.
        case mapValue(Mongorpc_MapValue)

        #if !swift(>=4.1)
            static func == (lhs: Mongorpc_Value.OneOf_ValueType, rhs: Mongorpc_Value.OneOf_ValueType) -> Bool {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch (lhs, rhs) {
                case (.nullValue, .nullValue): return {
                        guard case let .nullValue(l) = lhs, case let .nullValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.booleanValue, .booleanValue): return {
                        guard case let .booleanValue(l) = lhs, case let .booleanValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.integerValue, .integerValue): return {
                        guard case let .integerValue(l) = lhs, case let .integerValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.doubleValue, .doubleValue): return {
                        guard case let .doubleValue(l) = lhs, case let .doubleValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.timestampValue, .timestampValue): return {
                        guard case let .timestampValue(l) = lhs, case let .timestampValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.stringValue, .stringValue): return {
                        guard case let .stringValue(l) = lhs, case let .stringValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.bytesValue, .bytesValue): return {
                        guard case let .bytesValue(l) = lhs, case let .bytesValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.geoPointValue, .geoPointValue): return {
                        guard case let .geoPointValue(l) = lhs, case let .geoPointValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.arrayValue, .arrayValue): return {
                        guard case let .arrayValue(l) = lhs, case let .arrayValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                case (.mapValue, .mapValue): return {
                        guard case let .mapValue(l) = lhs, case let .mapValue(r) = rhs else { preconditionFailure() }
                        return l == r
                    }()
                default: return false
                }
            }
        #endif
    }

    init() {}
}

struct Mongorpc_ListCollectionsRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var database = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

struct Mongorpc_ListCollectionsResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var fields: [String: Mongorpc_Value] = [:]

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "mongorpc"

extension Mongorpc_NullValue: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "NULL_VALUE"),
    ]
}

extension Mongorpc_LatLng: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".LatLng"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "latitude"),
        2: .same(proto: "longitude"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularDoubleField(value: &self.latitude) }()
            case 2: try { try decoder.decodeSingularDoubleField(value: &self.longitude) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if latitude != 0 {
            try visitor.visitSingularDoubleField(value: latitude, fieldNumber: 1)
        }
        if longitude != 0 {
            try visitor.visitSingularDoubleField(value: longitude, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_LatLng, rhs: Mongorpc_LatLng) -> Bool {
        if lhs.latitude != rhs.latitude { return false }
        if lhs.longitude != rhs.longitude { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Mongorpc_Timestamp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".Timestamp"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "seconds"),
        2: .same(proto: "nanos"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularInt64Field(value: &self.seconds) }()
            case 2: try { try decoder.decodeSingularInt32Field(value: &self.nanos) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if seconds != 0 {
            try visitor.visitSingularInt64Field(value: seconds, fieldNumber: 1)
        }
        if nanos != 0 {
            try visitor.visitSingularInt32Field(value: nanos, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_Timestamp, rhs: Mongorpc_Timestamp) -> Bool {
        if lhs.seconds != rhs.seconds { return false }
        if lhs.nanos != rhs.nanos { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Mongorpc_ArrayValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ArrayValue"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "values"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !values.isEmpty {
            try visitor.visitRepeatedMessageField(value: values, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_ArrayValue, rhs: Mongorpc_ArrayValue) -> Bool {
        if lhs.values != rhs.values { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Mongorpc_MapValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".MapValue"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "fields"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString, Mongorpc_Value>.self, value: &self.fields) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !fields.isEmpty {
            try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString, Mongorpc_Value>.self, value: fields, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_MapValue, rhs: Mongorpc_MapValue) -> Bool {
        if lhs.fields != rhs.fields { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Mongorpc_Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".Value"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        11: .standard(proto: "null_value"),
        1: .standard(proto: "boolean_value"),
        2: .standard(proto: "integer_value"),
        3: .standard(proto: "double_value"),
        10: .standard(proto: "timestamp_value"),
        17: .standard(proto: "string_value"),
        18: .standard(proto: "bytes_value"),
        8: .standard(proto: "geo_point_value"),
        9: .standard(proto: "array_value"),
        6: .standard(proto: "map_value"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try {
                    var v: Bool?
                    try decoder.decodeSingularBoolField(value: &v)
                    if let v = v {
                        if self.valueType != nil { try decoder.handleConflictingOneOf() }
                        self.valueType = .booleanValue(v)
                    }
                }()
            case 2: try {
                    var v: Int64?
                    try decoder.decodeSingularInt64Field(value: &v)
                    if let v = v {
                        if self.valueType != nil { try decoder.handleConflictingOneOf() }
                        self.valueType = .integerValue(v)
                    }
                }()
            case 3: try {
                    var v: Double?
                    try decoder.decodeSingularDoubleField(value: &v)
                    if let v = v {
                        if self.valueType != nil { try decoder.handleConflictingOneOf() }
                        self.valueType = .doubleValue(v)
                    }
                }()
            case 6: try {
                    var v: Mongorpc_MapValue?
                    var hadOneofValue = false
                    if let current = self.valueType {
                        hadOneofValue = true
                        if case let .mapValue(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v = v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.valueType = .mapValue(v)
                    }
                }()
            case 8: try {
                    var v: Mongorpc_LatLng?
                    var hadOneofValue = false
                    if let current = self.valueType {
                        hadOneofValue = true
                        if case let .geoPointValue(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v = v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.valueType = .geoPointValue(v)
                    }
                }()
            case 9: try {
                    var v: Mongorpc_ArrayValue?
                    var hadOneofValue = false
                    if let current = self.valueType {
                        hadOneofValue = true
                        if case let .arrayValue(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v = v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.valueType = .arrayValue(v)
                    }
                }()
            case 10: try {
                    var v: Mongorpc_Timestamp?
                    var hadOneofValue = false
                    if let current = self.valueType {
                        hadOneofValue = true
                        if case let .timestampValue(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v = v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.valueType = .timestampValue(v)
                    }
                }()
            case 11: try {
                    var v: Mongorpc_NullValue?
                    try decoder.decodeSingularEnumField(value: &v)
                    if let v = v {
                        if self.valueType != nil { try decoder.handleConflictingOneOf() }
                        self.valueType = .nullValue(v)
                    }
                }()
            case 17: try {
                    var v: String?
                    try decoder.decodeSingularStringField(value: &v)
                    if let v = v {
                        if self.valueType != nil { try decoder.handleConflictingOneOf() }
                        self.valueType = .stringValue(v)
                    }
                }()
            case 18: try {
                    var v: Data?
                    try decoder.decodeSingularBytesField(value: &v)
                    if let v = v {
                        if self.valueType != nil { try decoder.handleConflictingOneOf() }
                        self.valueType = .bytesValue(v)
                    }
                }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch valueType {
        case .booleanValue?: try {
                guard case let .booleanValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
            }()
        case .integerValue?: try {
                guard case let .integerValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
            }()
        case .doubleValue?: try {
                guard case let .doubleValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
            }()
        case .mapValue?: try {
                guard case let .mapValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
            }()
        case .geoPointValue?: try {
                guard case let .geoPointValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
            }()
        case .arrayValue?: try {
                guard case let .arrayValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
            }()
        case .timestampValue?: try {
                guard case let .timestampValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
            }()
        case .nullValue?: try {
                guard case let .nullValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularEnumField(value: v, fieldNumber: 11)
            }()
        case .stringValue?: try {
                guard case let .stringValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularStringField(value: v, fieldNumber: 17)
            }()
        case .bytesValue?: try {
                guard case let .bytesValue(v)? = self.valueType else { preconditionFailure() }
                try visitor.visitSingularBytesField(value: v, fieldNumber: 18)
            }()
        case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_Value, rhs: Mongorpc_Value) -> Bool {
        if lhs.valueType != rhs.valueType { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Mongorpc_ListCollectionsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ListCollectionsRequest"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "database"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularStringField(value: &self.database) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !database.isEmpty {
            try visitor.visitSingularStringField(value: database, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_ListCollectionsRequest, rhs: Mongorpc_ListCollectionsRequest) -> Bool {
        if lhs.database != rhs.database { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Mongorpc_ListCollectionsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ListCollectionsResponse"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "fields"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString, Mongorpc_Value>.self, value: &self.fields) }()
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !fields.isEmpty {
            try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString, Mongorpc_Value>.self, value: fields, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Mongorpc_ListCollectionsResponse, rhs: Mongorpc_ListCollectionsResponse) -> Bool {
        if lhs.fields != rhs.fields { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
