// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mongorpc/value.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2021 MongoRPC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Null is a special type that is used to represent a null value in a MongoDB
enum Mongorpc_NullValue: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case nullValue // = 0
  case UNRECOGNIZED(Int)

  init() {
    self = .nullValue
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .nullValue
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .nullValue: return 0
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Mongorpc_NullValue: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Mongorpc_NullValue] = [
    .nullValue,
  ]
}

#endif  // swift(>=4.2)

struct Mongorpc_Empty {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Array is a special type that is used to represent an array value in a MongoDB
struct Mongorpc_ArrayValue {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var values: [Mongorpc_Value] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Map is a special type that is used to represent a map value in a MongoDB
struct Mongorpc_MapValue {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fields: Dictionary<String,Mongorpc_Value> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Timestamp is a special type that is used to represent a timestamp value in a MongoDB
struct Mongorpc_Timestamp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var seconds: Int64 = 0

  var nanos: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Mongorpc_ObjectId {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Value is a special type that is used to represent a value in a MongoDB
struct Mongorpc_Value {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Mongorpc_Value.OneOf_Type? = nil

  var integer32Value: Int32 {
    get {
      if case .integer32Value(let v)? = type {return v}
      return 0
    }
    set {type = .integer32Value(newValue)}
  }

  var integer64Value: Int64 {
    get {
      if case .integer64Value(let v)? = type {return v}
      return 0
    }
    set {type = .integer64Value(newValue)}
  }

  var booleanValue: Bool {
    get {
      if case .booleanValue(let v)? = type {return v}
      return false
    }
    set {type = .booleanValue(newValue)}
  }

  var stringValue: String {
    get {
      if case .stringValue(let v)? = type {return v}
      return String()
    }
    set {type = .stringValue(newValue)}
  }

  var doubleValue: Double {
    get {
      if case .doubleValue(let v)? = type {return v}
      return 0
    }
    set {type = .doubleValue(newValue)}
  }

  var nullValue: Mongorpc_NullValue {
    get {
      if case .nullValue(let v)? = type {return v}
      return .nullValue
    }
    set {type = .nullValue(newValue)}
  }

  var arrayValue: Mongorpc_ArrayValue {
    get {
      if case .arrayValue(let v)? = type {return v}
      return Mongorpc_ArrayValue()
    }
    set {type = .arrayValue(newValue)}
  }

  var mapValue: Mongorpc_MapValue {
    get {
      if case .mapValue(let v)? = type {return v}
      return Mongorpc_MapValue()
    }
    set {type = .mapValue(newValue)}
  }

  var objectIDValue: Mongorpc_ObjectId {
    get {
      if case .objectIDValue(let v)? = type {return v}
      return Mongorpc_ObjectId()
    }
    set {type = .objectIDValue(newValue)}
  }

  var timestampValue: Mongorpc_Timestamp {
    get {
      if case .timestampValue(let v)? = type {return v}
      return Mongorpc_Timestamp()
    }
    set {type = .timestampValue(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Type: Equatable {
    case integer32Value(Int32)
    case integer64Value(Int64)
    case booleanValue(Bool)
    case stringValue(String)
    case doubleValue(Double)
    case nullValue(Mongorpc_NullValue)
    case arrayValue(Mongorpc_ArrayValue)
    case mapValue(Mongorpc_MapValue)
    case objectIDValue(Mongorpc_ObjectId)
    case timestampValue(Mongorpc_Timestamp)

  #if !swift(>=4.1)
    static func ==(lhs: Mongorpc_Value.OneOf_Type, rhs: Mongorpc_Value.OneOf_Type) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.integer32Value, .integer32Value): return {
        guard case .integer32Value(let l) = lhs, case .integer32Value(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.integer64Value, .integer64Value): return {
        guard case .integer64Value(let l) = lhs, case .integer64Value(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.booleanValue, .booleanValue): return {
        guard case .booleanValue(let l) = lhs, case .booleanValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.stringValue, .stringValue): return {
        guard case .stringValue(let l) = lhs, case .stringValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.doubleValue, .doubleValue): return {
        guard case .doubleValue(let l) = lhs, case .doubleValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.nullValue, .nullValue): return {
        guard case .nullValue(let l) = lhs, case .nullValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.arrayValue, .arrayValue): return {
        guard case .arrayValue(let l) = lhs, case .arrayValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.mapValue, .mapValue): return {
        guard case .mapValue(let l) = lhs, case .mapValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.objectIDValue, .objectIDValue): return {
        guard case .objectIDValue(let l) = lhs, case .objectIDValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.timestampValue, .timestampValue): return {
        guard case .timestampValue(let l) = lhs, case .timestampValue(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  init() {}
}

/// ChangeStreamOptions represents options that can be used to configure a Watch operation.
struct Mongorpc_ChangeStreamOptions {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var batchSize: Int32 = 0

  var fullDocument: Bool = false

  var startAtOperationTime: Mongorpc_Timestamp {
    get {return _startAtOperationTime ?? Mongorpc_Timestamp()}
    set {_startAtOperationTime = newValue}
  }
  /// Returns true if `startAtOperationTime` has been explicitly set.
  var hasStartAtOperationTime: Bool {return self._startAtOperationTime != nil}
  /// Clears the value of `startAtOperationTime`. Subsequent reads from it will return its default value.
  mutating func clearStartAtOperationTime() {self._startAtOperationTime = nil}

  var maxAwaitTimeMs: Mongorpc_Timestamp {
    get {return _maxAwaitTimeMs ?? Mongorpc_Timestamp()}
    set {_maxAwaitTimeMs = newValue}
  }
  /// Returns true if `maxAwaitTimeMs` has been explicitly set.
  var hasMaxAwaitTimeMs: Bool {return self._maxAwaitTimeMs != nil}
  /// Clears the value of `maxAwaitTimeMs`. Subsequent reads from it will return its default value.
  mutating func clearMaxAwaitTimeMs() {self._maxAwaitTimeMs = nil}

  var resumeAfter: Mongorpc_Value {
    get {return _resumeAfter ?? Mongorpc_Value()}
    set {_resumeAfter = newValue}
  }
  /// Returns true if `resumeAfter` has been explicitly set.
  var hasResumeAfter: Bool {return self._resumeAfter != nil}
  /// Clears the value of `resumeAfter`. Subsequent reads from it will return its default value.
  mutating func clearResumeAfter() {self._resumeAfter = nil}

  var collation: Mongorpc_Value {
    get {return _collation ?? Mongorpc_Value()}
    set {_collation = newValue}
  }
  /// Returns true if `collation` has been explicitly set.
  var hasCollation: Bool {return self._collation != nil}
  /// Clears the value of `collation`. Subsequent reads from it will return its default value.
  mutating func clearCollation() {self._collation = nil}

  var startAfter: Mongorpc_Value {
    get {return _startAfter ?? Mongorpc_Value()}
    set {_startAfter = newValue}
  }
  /// Returns true if `startAfter` has been explicitly set.
  var hasStartAfter: Bool {return self._startAfter != nil}
  /// Clears the value of `startAfter`. Subsequent reads from it will return its default value.
  mutating func clearStartAfter() {self._startAfter = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _startAtOperationTime: Mongorpc_Timestamp? = nil
  fileprivate var _maxAwaitTimeMs: Mongorpc_Timestamp? = nil
  fileprivate var _resumeAfter: Mongorpc_Value? = nil
  fileprivate var _collation: Mongorpc_Value? = nil
  fileprivate var _startAfter: Mongorpc_Value? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "mongorpc"

extension Mongorpc_NullValue: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NULL_VALUE"),
  ]
}

extension Mongorpc_Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Empty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_Empty, rhs: Mongorpc_Empty) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mongorpc_ArrayValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ArrayValue"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "values"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_ArrayValue, rhs: Mongorpc_ArrayValue) -> Bool {
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mongorpc_MapValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapValue"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "fields"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Mongorpc_Value>.self, value: &self.fields) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fields.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Mongorpc_Value>.self, value: self.fields, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_MapValue, rhs: Mongorpc_MapValue) -> Bool {
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mongorpc_Timestamp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Timestamp"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "seconds"),
    2: .same(proto: "nanos"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.seconds) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.nanos) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.seconds != 0 {
      try visitor.visitSingularInt64Field(value: self.seconds, fieldNumber: 1)
    }
    if self.nanos != 0 {
      try visitor.visitSingularInt32Field(value: self.nanos, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_Timestamp, rhs: Mongorpc_Timestamp) -> Bool {
    if lhs.seconds != rhs.seconds {return false}
    if lhs.nanos != rhs.nanos {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mongorpc_ObjectId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ObjectId"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_ObjectId, rhs: Mongorpc_ObjectId) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mongorpc_Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Value"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "integer32_value"),
    2: .standard(proto: "integer64_value"),
    3: .standard(proto: "boolean_value"),
    4: .standard(proto: "string_value"),
    5: .standard(proto: "double_value"),
    6: .standard(proto: "null_value"),
    7: .standard(proto: "array_value"),
    8: .standard(proto: "map_value"),
    9: .standard(proto: "object_id_value"),
    10: .standard(proto: "timestamp_value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.type != nil {try decoder.handleConflictingOneOf()}
          self.type = .integer32Value(v)
        }
      }()
      case 2: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.type != nil {try decoder.handleConflictingOneOf()}
          self.type = .integer64Value(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.type != nil {try decoder.handleConflictingOneOf()}
          self.type = .booleanValue(v)
        }
      }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.type != nil {try decoder.handleConflictingOneOf()}
          self.type = .stringValue(v)
        }
      }()
      case 5: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.type != nil {try decoder.handleConflictingOneOf()}
          self.type = .doubleValue(v)
        }
      }()
      case 6: try {
        var v: Mongorpc_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.type != nil {try decoder.handleConflictingOneOf()}
          self.type = .nullValue(v)
        }
      }()
      case 7: try {
        var v: Mongorpc_ArrayValue?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .arrayValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .arrayValue(v)
        }
      }()
      case 8: try {
        var v: Mongorpc_MapValue?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .mapValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .mapValue(v)
        }
      }()
      case 9: try {
        var v: Mongorpc_ObjectId?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .objectIDValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .objectIDValue(v)
        }
      }()
      case 10: try {
        var v: Mongorpc_Timestamp?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .timestampValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .timestampValue(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .integer32Value?: try {
      guard case .integer32Value(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }()
    case .integer64Value?: try {
      guard case .integer64Value(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    }()
    case .booleanValue?: try {
      guard case .booleanValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case .doubleValue?: try {
      guard case .doubleValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 5)
    }()
    case .nullValue?: try {
      guard case .nullValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 6)
    }()
    case .arrayValue?: try {
      guard case .arrayValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .mapValue?: try {
      guard case .mapValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .objectIDValue?: try {
      guard case .objectIDValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .timestampValue?: try {
      guard case .timestampValue(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_Value, rhs: Mongorpc_Value) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mongorpc_ChangeStreamOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChangeStreamOptions"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "batch_size"),
    3: .standard(proto: "full_document"),
    4: .standard(proto: "start_at_operation_time"),
    5: .standard(proto: "max_await_time_ms"),
    6: .standard(proto: "resume_after"),
    7: .same(proto: "collation"),
    8: .standard(proto: "start_after"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.batchSize) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.fullDocument) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._startAtOperationTime) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._maxAwaitTimeMs) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._resumeAfter) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._collation) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._startAfter) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.batchSize != 0 {
      try visitor.visitSingularInt32Field(value: self.batchSize, fieldNumber: 1)
    }
    if self.fullDocument != false {
      try visitor.visitSingularBoolField(value: self.fullDocument, fieldNumber: 3)
    }
    try { if let v = self._startAtOperationTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._maxAwaitTimeMs {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._resumeAfter {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._collation {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._startAfter {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mongorpc_ChangeStreamOptions, rhs: Mongorpc_ChangeStreamOptions) -> Bool {
    if lhs.batchSize != rhs.batchSize {return false}
    if lhs.fullDocument != rhs.fullDocument {return false}
    if lhs._startAtOperationTime != rhs._startAtOperationTime {return false}
    if lhs._maxAwaitTimeMs != rhs._maxAwaitTimeMs {return false}
    if lhs._resumeAfter != rhs._resumeAfter {return false}
    if lhs._collation != rhs._collation {return false}
    if lhs._startAfter != rhs._startAfter {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
